#!/bin/bash
set -e

IMAGE="ghcr.io/andreluis933/webhook-sms:latest"
CONTAINER_NAME="webhook-sms"
ENV_FILE="/projects/webhook-sms/.env"

echo "[$(date)] Atualizando imagem..."
docker pull "$IMAGE"

echo "[$(date)] Iniciando scraper..."
docker run --rm \
  --name "$CONTAINER_NAME" \
  --network redis-network \
  --env-file "$ENV_FILE" \
  "$IMAGE"

echo "[$(date)] Scraper finalizado!"
docker image prune -f